name: Python test

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
        env:
          CI: 1

      - name: Lint with flake8
        run: |
          pipenv run flake8 server tests --count --show-source --statistics
