name: test frontend

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.10.x'

      - run: yarn install
      - run: yarn test --watchAll=false
