name: Python test

on:
  push:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Set up Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: 'hms-test'

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 server --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pipenv run test tests
        env:
          DATABASE_URL: postgresql://hms-test
          REACT_APP_SERVER_URL: http://localhost:5000
          SENDGRID_API_KEY: test
          SECRET_KEY: test
