name: Python test

on:
  push:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-18.04

    container:
      image: python:3

    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
        env:
          CI: 1

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 server --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pipenv run test tests
        env:
          DATABASE_URL: postgresql:///postgres:postgres@postgres:${{ job.services.postgres.ports[5432] }}/postgres
          REACT_APP_SERVER_URL: http://localhost:5000
          SENDGRID_API_KEY: test
          SECRET_KEY: test
