name: Python lint and test

on:
  push:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-18.04

  steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 server --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pipenv run pytest
